// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.fuchsia:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for fuchsia - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZZjqjCKRVSPnVTqeApVzq_8qTzVcnesY',
    authDomain: 'evem-a97e0.firebaseapp.com',
    projectId: 'evem-a97e0',
    storageBucket: 'evem-a97e0.appspot.com',
    messagingSenderId: '283020318458',
    appId: '1:283020318458:web:d335c31710919a77029b43',
    measurementId: 'G-6RQFJR5KGG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'YOUR_API_KEY', // Replace with your Android API key
    appId: 'YOUR_APP_ID', // Replace with your Android app ID
    messagingSenderId: '283020318458',
    projectId: 'evem-a97e0',
    storageBucket: 'evem-a97e0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'YOUR_API_KEY', // Replace with your iOS API key
    appId: 'YOUR_APP_ID', // Replace with your iOS app ID
    messagingSenderId: '283020318458',
    projectId: 'evem-a97e0',
    storageBucket: 'evem-a97e0.appspot.com',
    iosBundleId: 'com.example.evem', // Replace with your iOS bundle ID
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'YOUR_API_KEY', // Replace with your macOS API key
    appId: 'YOUR_APP_ID', // Replace with your macOS app ID
    messagingSenderId: '283020318458',
    projectId: 'evem-a97e0',
    storageBucket: 'evem-a97e0.appspot.com',
    iosBundleId: 'com.example.evem', // Replace with your macOS bundle ID
  );
}
